### ISSUE TITLE
Remove promoted posts and advertorials on LinkedIn

### ISSUE THREAD

**Issue by VanHamsteren** [xvello/letsblockit#129]
### What website(s) would this filter apply to?

linkedin.com

### What content should be blocked?

Promoted posts or advertorials

### Did you write a custom uBlock filter already?

English:
linkedin.com##span:has-text(Promoted):upward(6)

Dutch:
linkedin.com##span:has-text(Gepromoot):upward(6)

**Comment by xvello** [comment]
Hi @VanHamsteren and thanks for opening this issue.

As I wrote in [the contributing guidelines](https://letsblock.it/help/contributing) there are great existing projects dedicated to blocking ads and I'd rather not duplicate their efforts.

Easylist already has [a multi-language rule to block sponsored posts](https://github.com/easylist/easylist/blob/d4ac72c1fb38fb5acecdfaba077b5a533a1c3ad9/easylist/easylist_specific_hide_abp.txt#L58-L59). Despite the filename, it is included in the version uBlockOrigin downloads (you can check this by clicking on the eye icon next to "Easylist" in you uBlockOrigin filter list).

I suggest you open a PR or issue there to add Dutch to the regex.

**Comment by xvello** [comment]
Opened a PR to easylist to add support for Dutch in their filter: https://github.com/easylist/easylist/pull/11902

You can subscribe to this PR to follow it's progress. I am closing this issue.
