### ISSUE TITLE
DuckDuckGo filters needs to update

### ISSUE THREAD

**Issue by hirorpt** [xvello/letsblockit#140]
### What filter does this issue target?

Hide websites from search results

### What changes should be made?

DuckDuckGo has made major changes to the structure of the site. You can't use the old filters at all.

### Did you write a uBlock filter solving this?

`duckduckgo.com##[href*="example.com"][data-testid="result-title-a"]:upward(.nrn-react-div)`

**Comment by xvello** [comment]
Thanks a lot @hirorpt, the fix is deployed. Don't forget to manually [refresh your list](https://letsblock.it/help/refresh-list).
