### ISSUE TITLE
Block Instagram post on description and alt text of image

### ISSUE THREAD

**Issue by BPower0036** [xvello/letsblockit#150]
### What website(s) would this filter apply to?

instagram.com

### What content should be blocked?

Instagram post based on the text in the desciption

### Did you write a custom uBlock filter already?

`##article:has([data-testid="post-comment-root"] span[class]:has-text(...))`
`##article:has(img[src][alt*="..."])`

**Comment by xvello** [comment]
Hello @BPower0036 and thanks for your suggestion.

Meta is a company I refuse to associate with, and as such I will not be adding any filter targeting its websites, as stated in [the contribution guidelines](https://letsblock.it/help/contributing).

**Comment by BPower0036** [comment]
I respect your choice! I should have read the contribution guidelines first.

**Comment by xvello** [comment]
Thanks for your understanding. 

If the project grows big enough and retains a team of filter maintainers, we could revisit the scope ; but in the meantime I'll only commit to what I can sustainably maintain.
