### ISSUE TITLE
youtube-cleanup: additional parameters

### ISSUE THREAD

**Issue by BPower0036** [xvello/letsblockit#152]
### What website(s) would this filter apply to?

www.youtube.com

### What content should be blocked?

I don't know if you would like it to add or if you find it necessary. 
But could it be a good idea to block the comment section / comments with certain words?
Above the title of some YT-video is shows some hashtags. Could it also be a good idea to block this?

If yes, read further.

### Did you write a custom uBlock filter already?

To hide the comment section completely
`www.youtube.com###comments #contents:remove()`
With `#contents` removing you can still see how many reactions there are + write your own reaction.
If it is only `www.youtube.com###comments:remove()` you can't see how many reactions there are nor write your own reaction anymore.

To hide only comment with certain words
`www.youtube.com###comment:has-text(...):upward(1)`

To hide the hashtags. The first one is for the newest layout; the second one for the older layout
`www.youtube.com###super-title`
`www.youtube.com##.super-title`

### Additional notes

For the hashtags it is the blue text in the image
`https://www.youtube.com/watch?v=nkoLchhy00g`
![afbeelding](https://user-images.githubusercontent.com/80090789/169380345-4b9c4e45-36c4-42e9-963c-b41e43204c68.png)

**Comment by xvello** [comment]
Implemented in https://github.com/xvello/letsblockit/pull/153 and https://github.com/xvello/letsblockit/pull/154, closing it.

I'll probably merge https://letsblock.it/filters/youtube-streams-chat back into `youtube-cleanup`, just need to investigate how to migrate settings for existing users.
