### ISSUE TITLE
Filters to remove "People also ask" on Google Search

### ISSUE THREAD

**Issue by Pccode66** [xvello/letsblockit#4]
I suggest adding the filter `google.*###rso > div:has(:scope > div > div > .xpdopen > div > div > [class$="related-question-pair"])` to hide the "People also ask" section that appears between Google search results. This is different from the smaller "People also ask" section that appears under a search result.

**Comment by xvello** [comment]
Hi @Pccode66, thanks for the suggestion!
I'll start a debloat-google filter for group these together, as there's other contextual snippets we'll want to remove too.

**Comment by xvello** [comment]
Heya @Pccode66, it's live at https://letsblock.it/filters/cleanup-google-search, thanks a lot!

- I had to make the filter less selective to match both the Firefox and Chrome markups
- I added my greedier (hide everything but `div.g` filter), but disabled by default, as it's a bit risqué

**Comment by krystian3w** [comment]
These worth hide in Google graphics?
```css
google.*#?##islrg div.isv-r:-abp-has( > div[class] > div[class]:-abp-contains(/^Similar (pages|searches)$/))
google.*#?#.isv-r:-abp-has( > div > div > h2:-abp-contains(/^Similar (pages|searches)$/))
```

PS my idea is language specific so need cover all Google translation needed.

**Comment by xvello** [comment]
Hello @krystian3w, I cannot see any section titled `Similar pages` or `Similar searches`, could you please provide links and snapshots of occurrences? As google is A/B testing continuously, you might be served new content I am not.

**Comment by krystian3w** [comment]
`https://www.google.com/search?q=arbre&tbm=isch`

![Screenshot_20220222-114022_Firefox.jpg](https://user-images.githubusercontent.com/35370833/155115842-0e70d07d-f2e8-49fc-bbb6-848ed490bccb.jpg) | ![Screenshot_20220222-113833_Firefox.jpg](https://user-images.githubusercontent.com/35370833/155115882-031ee51c-14a9-4223-87ee-f7ff595ffb88.jpg) | ![Screenshot_20220222-113812_Firefox.jpg](https://user-images.githubusercontent.com/35370833/155115944-1b716fcf-6ca4-4275-8253-0c58e864e405.jpg) |
- | - | - |

IMO this is not A/B test - this was added in ≈2019 and exist to today

**Comment by xvello** [comment]
Thanks, I was looking at text results only.

Good catch on the `isv-r` class: it does not match their minification taxonomy, so it might be stable enough.
It looks like `<h2>` is only used for these contextual results, so I think we should go with the following filter:

```
##h2:upward(div.isv-r)
```

What do you think?

**Comment by krystian3w** [comment]
IMO Looks good, a little pity is depletion ID form all graphics results in mobile view - PC have `#islrg`.

**Comment by xvello** [comment]
> a little pity is deletion ID form all graphics results in mobile view

Sorry, I could not understand what the side effect is here. I tried `google.*##h2:upward(div.isv-r):style(background:red)` on Firefox Mobile and could not find other red spans than the intended blocks.

Could you please rephrase this? French is OK too.

**Comment by krystian3w** [comment]
I mean mobile layout can not use `###islrg h2...` if Google start use `.isv-r` in other places (unexpected combo with h2).

Also still works reddit method then possible add simple:

`##[data-rfg]`

Should minimize chance to blink in first row (browser CSS logic).


---

About leftovers at right if you see these - Google search no longer use one big div and this can be fixed by rewrite CSS or rebuild nodes if someone have idea (rebuild nodes may need requirements use something like tampermonkey).

**Comment by xvello** [comment]
Thanks for the explanation! I saw the `data-rfg` attribute, but was not sure whether it would be stable enough.

I am going with `google.*##div.isv-r[data-rfg]` for performance, and we can update it if it breaks in the future.

**Comment by xvello** [comment]
@krystian3w  New param deployed now! 
Don't forget to enable it in https://letsblock.it/filters/google-search-cleanup and refresh your list in uBO.
