### ISSUE TITLE
Block suggested videos on YouTube landing page

### ISSUE THREAD

**Issue by link2xt** [xvello/letsblockit#49]
### What website(s) would this filter apply to?

youtube.com

### What content should be blocked?

All the video thumbnails on YouTube landing page.

### Did you write a custom uBlock filter already?

```
youtube.com##ytd-browse[page-subtype="home"]
```

**Comment by xvello** [comment]
Thanks for your contribution :bow: 
I merged both filters in https://letsblock.it/filters/youtube-recommendations
