### ISSUE TITLE
hide the google search footer

### ISSUE THREAD

**Issue by h3oCharles** [xvello/letsblockit#70]
### What website(s) would this filter apply to?

google.com

### What content should be blocked?

at the bottom of the google search page, there's a footer that can contain one's address, which could doxx someone by accident

![image](https://user-images.githubusercontent.com/8020330/153724757-b1ebb872-e44a-4b14-b732-19e74be19fbd.png)

### Did you write a custom uBlock filter already?

www.google.com###fbarcnt

**Comment by xvello** [comment]
Thanks for the issue!

I added the option in the [google-search-cleanup](https://letsblock.it/filters/google-search-cleanup) template. I am leaving it disabled by default, because the "Update location" might be useful to some.

Have a great weekend!
