### ISSUE TITLE
block google image results by domain

### ISSUE THREAD

**Issue by h3oCharles** [xvello/letsblockit#71]
### What website(s) would this filter apply to?

google.com or images.google.com

### What content should be blocked?

each image result that comes from a specified domain

main offenders could be:
pinterest.com, shutterstock.com, vectorstock.com, istockphoto.com, dreamstime.com, gettyimages.com

![image](https://user-images.githubusercontent.com/8020330/153724927-3f13c000-a496-4800-b664-7665db9c7c21.png)
![image](https://user-images.githubusercontent.com/8020330/153724997-03efdc23-cf4c-4675-abdd-bd9f92eb08d0.png)

### What options should be offered?

specifying each domain

**Comment by xvello** [comment]
Hello @h3oCharles and thanks for your report.

It looks like you are looking for the [search-results](https://letsblock.it/filters/search-results) filter template, that hides results on both the text and image results for all supported websites. Could you please test it and tell me whether it fits your use case?

**Comment by h3oCharles** [comment]
yup, that did it
