### ISSUE TITLE
Exclude tweets from Twitter searches by username without login

### ISSUE THREAD

**Issue by hirorpt** [xvello/letsblockit#74]
### What website(s) would this filter apply to?

twitter.com

### What content should be blocked?

There are no ways to block or mute users without twitter login. However when you search Twitter, many spam bots prevent you from finding valuable information. I regularly search Twitter for certain words  and currently use about 10 filters that excludes spam accounts for best results. 
Search operator `-from:$USERNAME` also works for the same purpose, but uBO filters has the advantage that once you add filters, exclusions work permanently for all searches. 

### What options should be offered?

The users must enter a list of usernames to block. 

There are several web services that offer Twitter search, for example, [nitter.net](https://github.com/zedeus/nitter). I don't think it's necessary, but you can consider the option of enabling cosmetic filters for them.

### Did you write a custom uBlock filter already?

Yes.
~~~
twitter.com##a[href="/$USERNAME"]:upward(article)
~~~

**Comment by xvello** [comment]
Hello @hirorpt, thanks for your contribution! I'll add filter for this.

While we are at it, do you feel like a filter on hashtags would be useful?

**Comment by hirorpt** [comment]
> While we are at it, do you feel like a filter on hashtags would be useful?

I am sorry for late reply, and very impressed with the prompt response.
For some reason I forgot about it when submitting this issue, but I'm also using that hashtag filters.
