### ISSUE TITLE
Bing.com - search-results

### ISSUE THREAD

**Issue by BPower0036** [xvello/letsblockit#79]
### What filter does this issue target?

search-results

### What changes should be made?

Add bing.com

### Did you write a uBlock filter solving this?

bing.com##[id$="results"] > :has(a[href*="facebook.com/"])

### Additional notes

Above where `facebook.com/` is the url

**Comment by xvello** [comment]
Hello @BPower0036, my bad for forgetting Bing !

The following filter works on both text and image search, and avoids the suffix match on `[id$="results"]`, would it be OK?
```
bing.com###b_content a[href*="{{site}}"]:upward(li)
```

**Comment by BPower0036** [comment]
Yes, that is fine.
My rule does only the text search.

**Comment by xvello** [comment]
@BPower0036 It's live at https://letsblock.it/filters/search-results , don't hesitate to re-open if things don't work 100%.
