### ISSUE TITLE
Very minor change to support SearXNG

### ISSUE THREAD

**Issue by katacarbix** [xvello/letsblockit#86]
### What filter does this issue target?

search-results

### What changes should be made?

In SearX, results are `div`s, while in SearXNG they are `article`s, so the rule:

```
searx.example.com###main_results div.result:has(a[href*=".pinterest."])
```

would not apply. Simply remove the `div` and it should work on both:

```
searx.example.com###main_results .result:has(a[href*=".pinterest."])
```

### Did you write a uBlock filter solving this?

```
searx.example.com###main_results .result:has(a[href*=".pinterest."])
```

### Additional notes

In case anyone needs convincing:

SearXNG is a fork of SearX with some (subjective) improvements to privacy and theming. It's become arguably the more popular version as of late, and even [searx.space](https://searx.space/) puts it first when talking about the two of them.

**Comment by xvello** [comment]
Thanks for the contribution @katacarbix, it is deploying right now!
